package com.demo.jiyun.pandatv.model.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.demo.jiyun.pandatv.model.db.Keep;
import com.demo.jiyun.pandatv.model.db.History;

import com.demo.jiyun.pandatv.model.db.KeepDao;
import com.demo.jiyun.pandatv.model.db.HistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig keepDaoConfig;
    private final DaoConfig historyDaoConfig;

    private final KeepDao keepDao;
    private final HistoryDao historyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        keepDaoConfig = daoConfigMap.get(KeepDao.class).clone();
        keepDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        keepDao = new KeepDao(keepDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);

        registerDao(Keep.class, keepDao);
        registerDao(History.class, historyDao);
    }
    
    public void clear() {
        keepDaoConfig.clearIdentityScope();
        historyDaoConfig.clearIdentityScope();
    }

    public KeepDao getKeepDao() {
        return keepDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

}
